config/routes.rb
Rails.application.routes.draw do
	#static pages
	root to: "static#main"
	get '/contacts', to: "static#contacts"

	#users
	devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks' }
	devise_scope :user do
		get 'sign_in', :to => 'devise/sessions#new' , :as => :new_user_session
		get 'sign_out', :to => 'devise/sessions#destroy' , :as => :destroy_user_session
	end
	match '/users/:id/finish_signup/:token' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
	#user's profile
	resources :users do
		resources :course_statistics, only: :show
	end

	#rating
	resources :ratings, only: :index

	#API
	namespace :api do
		resources :users, only: :show do
			resources :courses, only: :show
		end

		resources :disciplines, only: :index do
			resources :questions, only: :show
		end
	end

	#courses
	resources :courses, only: [:show, :index] do

		#lessons
		resources :lessons, only: [:show, :index] do
			#surveys
			resources :survey_attempts, only: [:new, :create, :show, :destroy] do
				resources :questions, except: :new
			end

			#homeworks
			resources :homeworks, only: [:new, :create]
		end
	end

	#admin dashboard
	namespace :admin do
		#disciplines
		resources :disciplines, except: :show do

			resources :extension_questions do
			end
		end

		#courses
		root to: 'courses#index'
		resources :courses, except: :show do

			#banks
			# get "questions", to: "banks#index"

			#course access
			get 'all_access', to: 'course_accesses#all_access'
			resources :course_accesses, only: [:index, :destroy, :create]

			#course teachers
			resources :teacher_courses, only: [:index, :create, :destroy]

			#lessons
			resources :lessons, except: :show do
				#questions
				resources :questions, except: :show

				#offline_survey_attempts
				resources :offline_survey_attempts, except: :show
			end
		end

		#homeworks
		resources :homework_attempts, only: [:show, :index, :update]

		#surveys
		resources :survey_attempts, only: [:index, :destroy]

		#roles
		post 'add_admin', to: 'roles#add_admin'
		post 'add_teacher', to: 'roles#add_teacher'

		post 'remove_admin', to: 'roles#remove_admin'
		post 'remove_teacher', to: 'roles#remove_teacher'
		resources :roles, only: :index

		#api for sortable lessons
		namespace :api do
			namespace :lessons do
				resource :mass_update, only: :create
			end
		end
	end
end

app/models/role.rb
class Role < ApplicationRecord
	has_many :users_roles
	has_many :users, through: :users_roles
end

app/controllers/admin/roles_controller.rb
class Admin::RolesController < Admin::AdminController
	before_action :can_access
	before_action :check_add_user, only: [:add_admin, :add_teacher]
	before_action :check_remove_user, only: [:remove_admin, :remove_teacher]

	def index
		@teachers = Role.find_by(name: :teacher).users
		@admins = Role.find_by(name: :admin).users
	end

	def add_admin
		User.find(role_params[:user_id]).roles << Role.find_by(name: :admin)
		redirect_to admin_roles_path, notice: "Привилегия добавлена"
	end

	def add_teacher
		User.find(role_params[:user_id]).roles << Role.find_by(name: :teacher)
		redirect_to admin_roles_path, notice: "Привилегия добавлена"
	end

	def remove_admin
		UsersRole.find_by(user_id: params[:user_id], role_id: Role.find_by(name: :admin).id).destroy
		redirect_to admin_roles_path, notice: "Привилегия удалена"
	end

	def remove_teacher
		UsersRole.find_by(user_id: params[:user_id], role_id: Role.find_by(name: :teacher).id).destroy
		redirect_to admin_roles_path, notice: "Привилегия удалена"
	end

	private
	def check_remove_user
		if User.find(params[:user_id]).nil?
			redirect_to admin_roles_path, notice: "Ошибка"
		end
	end

	def check_add_user
		if User.find(role_params[:user_id]).nil?
			redirect_to admin_roles_path, notice: "Ошибка"
		end
	end

	def set_active_header_item
		@header[:users][:active] = true
	end

	def role_params
		params.require(:users).permit(:user_id)
	end

	def can_access
		unless current_user.is_admin?
			redirect_to admin_root_path, notice: "У вас нет доступа к этой странице"
		end
	end
end

app/helpers/admin/roles_helper.rb
module Admin::RolesHelper
	def users_without_admin_privs
		User.all - Role.find_by(name: :admin).users
	end

	def users_without_teacher_privs
		User.all - Role.find_by(name: :teacher).users
	end
end

app/views/admin/roles/index.html.erb
<h3 class="float-left">Админы сайта</h3>

<table class="table table-striped">
	<%= simple_form_for(:users, url: admin_add_admin_path, method: :post, wrapper: :horizontal_form, html: { class: 'form-horizontal' }) do |f| %>
		<%= f.input :user_id, collection: users_without_admin_privs, label_method: :full_name %>

		<div class="button-box float-right">
			<%= f.submit "Сохранить", class: 'btn btn-primary' %>
		</div>
	<% end %>
	<thead>
		<tr>
			<th>Пользователь</th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		<% @admins.each do |a| %>
			<tr>
				<td><%= link_to a.full_name, a %></td>
				<td><%= link_to 'Удалить', admin_remove_admin_path(user_id: a.id), class: "btn btn-danger btn-sm", method: :post, data: {confirm: "Вы уверены?"} %></td>
			</tr>
		<% end %>
	</tbody>
</table>

<h3 class="float-left">Преподаватели сайта</h3>

<table class="table table-striped">
	<%= simple_form_for(:users, url: admin_add_teacher_path, method: :post, wrapper: :horizontal_form, html: { class: 'form-horizontal' }) do |f| %>
		<%= f.input :user_id, collection: users_without_teacher_privs, label_method: :full_name %>

		<div class="button-box float-right">
			<%= f.submit "Сохранить", class: 'btn btn-primary' %>
		</div>
	<% end %>
	<thead>
		<tr>
			<th>Пользователь</th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		<% @teachers.each do |a| %>
			<tr>
				<td><%= link_to a.full_name, a %></td>
				<td><%= link_to 'Удалить', admin_remove_teacher_path(user_id: a.id), class: "btn btn-danger btn-sm", method: :post, data: {confirm: "Вы уверены?"} %></td>
			</tr>
		<% end %>
	</tbody>
</table>